--------------------------------------------------------
--  Fichier créé - samedi-octobre-08-2022   
--------------------------------------------------------
REM INSERTING into INSTRUMENT
SET DEFINE OFF;
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values (25, 18, to_date('07/09/21','DD/MM/RR'), 47.56,'Bois Pin','Thomann','TK14');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values (26, 18, to_date('07/09/21','DD/MM/RR'), 41.23,'Bois Acajou','Artisanat',null);
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values ( 1,  2, to_date('15/09/11','DD/MM/RR'), 1500,'Doré','Yamaha','YAS-280');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values (23,  5, to_date('01/09/19','DD/MM/RR'), 1369,'Bleu nuit','CoolWind','CTU-200DB');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values ( 2,  4, to_date('06/06/10','DD/MM/RR'), 2785,'Noir','Yamaha','YCL-221II');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values ( 3,  4, to_date('06/06/16','DD/MM/RR'), 2785,'Noir','Yamaha','YCL-221II');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values ( 4,  1, to_date('12/12/10','DD/MM/RR'), 150,'Orange','CoolWind','CTR-200OG');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values ( 5,  5, to_date('14/09/15','DD/MM/RR'), 2190,'Doré','Jupiter','JPT-020');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values ( 6,  2, to_date('09/09/18','DD/MM/RR'), 880,'Doré','Jupiter','JAS500Q');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values ( 7,  2, to_date('09/09/18','DD/MM/RR'), 880,'Doré','Jupiter','JAS500Q');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values ( 8,  3, to_date('01/09/11','DD/MM/RR'), 800,'Argenté','Pearl Quantz','505R');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values (10,  4, to_date('01/06/18','DD/MM/RR'), 1000,'Noir','Leblanc','CL-501');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values (11,  2, to_date('15/09/11','DD/MM/RR'), 1500,'Doré','Yamaha','YAS-280');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values (12,  2, to_date('15/09/11','DD/MM/RR'), 1500,'Doré','Yamaha','YAS-280');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values (13,  3, to_date('01/09/12','DD/MM/RR'), 670,'Argenté','Pearl Quantz','F505R');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values (14,  8, to_date('08/06/18','DD/MM/RR'), 629,'Doré','Jupiter','JPT-500Q');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values (15,  8, to_date('08/06/18','DD/MM/RR'), 629,'Doré','Jupiter','JPT-500Q');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values (16, 14, to_date('05/05/10','DD/MM/RR'), 350,'Doré','Yamaha','YCR-2330');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values (17, 14, to_date('05/05/10','DD/MM/RR'), 420,'Argenté','SML VSM','CO 505');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values (18, 14, to_date('05/05/10','DD/MM/RR'), 420,'Argenté','SML VSM','CO 505');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values (19,  1, to_date('12/12/17','DD/MM/RR'), 150,'Rouge','CoolWind','CTR-200RD');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values (20,  1, to_date('12/12/17','DD/MM/RR'), 150,'Rouge','CoolWind','CTR-200RD');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values (21,  3, to_date('01/09/18','DD/MM/RR'), 720,'Argenté','Pearl Quantz','F505R');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values (22, 15, to_date('01/09/19','DD/MM/RR'), 495,'Rouge','CoolWind','CEU-200RD');
Insert into INSTRUMENT (IDINST,IDTPINST,DATEACHAT,PRIXACHAT,COULEUR,MARQUE,MODELE) values (24, 17, to_date('25/09/21','DD/MM/RR'), 38.89,'Rouge-Jaune','Thomann','L''albator soprano');
